- name: Install All Applications on RDSH
  hosts: all
  collections:
    - community.windows
    - chocolatey.chocolatey
  tasks:
  - name: Install Chrome
    win_chocolatey:
      name: googlechrome
      state: present