- name: Install All Applications on RDSH
  hosts: all
  collections:
    - community.windows
    - chocolatey.chocolatey
    - ansible.windows
  tasks:
  - win_domain_membership:
      dns_domain_name: '{{ domain }}'
      hostname: '{{ inventory_hostname }}'
      domain_admin_user: testadmin@yourdomain.local
      domain_admin_password: P@$$w0rd!
      domain_ou_path: "OU=Windows,OU=Servers,DC=yourdomain,DC=local"
      state: domain
    register: domain_state

  - win_reboot:
    when: domain_state.reboot_required

  - name: Install Chrome
    win_chocolatey:
      name: googlechrome
      state: present

  - name: Install 7 Zip
    win_chocolatey:
      name: 7zip
      state: present

  - name: Install Adobe Reader
    win_chocolatey:
      name: adobereader
      state: present

  - name: Install Greenshot
    win_chocolatey:
      name: greenshot
      state: present

  - name: Install FSlogix
    win_chocolatey:
      name: fslogix
      state: present

  - name: Install FSlogix-Rule
    win_chocolatey:
      name: fslogix-rule
      state: present

  - name: Install OneDrive
    win_chocolatey:
      name: onedrive
      state: present

  - name: Install Microsoft Teams
    win_chocolatey:
      name: microsoft-teams
      state: present

  - name: Install Firefox
    win_chocolatey:
      name: firefox
      state: present

  - name: Install WinSCP
    win_chocolatey:
      name: winscp
      state: present

#  - name: Install all updates and reboot as many times as needed
#    ansible.windows.win_updates:
#      category_names: '*'
#      reboot: false

  - name: Add Domain Group to FSlogix ODFC
    ansible.windows.win_group_membership:
      name: FSLogix ODFC Include List
      members:
        - DRKHG\FSLogix-Access
      state: pure

  - name: Add Domain Group to FSlogix Profiles
    ansible.windows.win_group_membership:
      name: FSLogix Profile Include List
      members:
        - DRKHG\FSLogix-Access
      state: pure
