- name: Install All Applications on RDSH
  hosts: all
  collections:
    - community.windows
  tasks:
  - name: install chocolatey
    win_chocolatey:
       name: chocolatey
       state: present
  - name: Install Chrome
    win_chocolatey:
      name: googlechrome
      state: present